[workspace]
resolver = "2"
members = [
    "command_center",
    "stt",
    "stt_api",
    "llm",
    "llm_api",
    "tg",
    "tg_api",
    "tg_yt_curation",
]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
