interface embedding {
    variant embedding-request {
        get-embeddings-for-texts(list<string>)
    }

    variant embedding-response {
        get-embeddings-for-texts(result<list<list<float32>>, string>)
    }
}

world embedding-uncentered-dot-os-api-v0 {
    export embedding;
}

world embedding-uncentered-dot-os-v0 {
    import embedding;
    include process-v0;
}